name: gate_control_device
description: "Gate Control Device v1.1 Hybrid - Foreground service + FCM wake-up"
publish_to: 'none'
version: 1.1.1+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.4
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  android_intent_plus: ^5.3.1
  permission_handler: ^11.0.1
  flutter_foreground_task: ^8.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
