name: gate_control_device
description: "Gate Control Device v1.1 - FCM based gate control with SMS retry"
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.4
  firebase_core: ^3.10.0
  firebase_messaging: ^15.1.6
  android_intent_plus: ^5.2.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
